A:
	cat Ainput.txt | python A.py
B:
	cat Binput.txt | python B.py
C:
	cat Cinput.txt | python C.py
D:
	cat Dinput.txt | python D.py
E:
	cat Einput.txt | python E.py
F:
	cat Finput.txt | python F.py
G:
	cat Ginput.txt | python G.py